image: mcr.microsoft.com/playwright:v1.56.0-noble

stages:
  - test
  - report

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CI: "true"

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

playwright-tests:
  stage: test
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test
  allow_failure: true
  artifacts:
    when: always
    paths:
      - allure-results/
    expire_in: 30 days

generate-allure-report:
  stage: report
  script:
    - npm ci
    - node scripts/save-history.js
    - npx allure generate allure-results --clean -o allure-report
    - node scripts/send-email-report.js
  artifacts:
    when: always
    paths:
      - allure-report/
    expire_in: 30 days
  dependencies:
    - playwright-tests
